#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM eclipse-temurin:8-jdk-centos7

ENV LANG C.UTF-8

WORKDIR /root
COPY code_run.sh /root/code_run.sh
RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
RUN chmod 755 /root/code_run.sh
RUN tar -xvf /root/apache-maven-3.8.7-bin.tar.gz -C /opt/
COPY settings.xml /opt/apache-maven-3.8.7/conf

RUN yum install unzip curl git epel-release gettext jq wget psmisc -y
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
RUN curl -fsSl https://kubevela.net/script/install.sh | bash

RUN wget -O go1.19.linux-amd64.tar.gz -q https://go.dev/dl/go1.19.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz && \
    rm go1.19.linux-amd64.tar.gz

RUN echo "export GOROOT=/usr/local/go" >> /root/.bashrc && \
    echo "export PATH=\$GOROOT/bin:\$PATH" >> /root/.bashrc && \
    echo "export GOPATH=/home/admin/code" >> /root/.bashrc && \
    echo "export GOPROXY=https://proxy.golang.com.cn,direct" >> /root/.bashrc && \
    echo "export GO111MODULE=on" >> /root/.bashrc && \
    echo "export GOSUMDB=off" >> /root/.bashrc && \
    echo "export GONOSUMDB=*.corp.example.com,rsc.io/private" >> /root/.bashrc && \
    source /root/.bashrc

ENV PATH="${PATH}:/opt/rh/devtoolset-7/root/usr/bin:/usr/local/go/bin"

RUN GO111MODULE="on" go install gotest.tools/gotestsum@latest && \
    ln -s /root/go/bin/gotestsum /usr/bin/gotestsum

WORKDIR /root
CMD ["/bin/bash", "-c", "./code_run.sh"]
